Inventario/urls.py
from django.urls import path
from . import views

urlpatterns = [
    #------------------------Index y login------------------------------------------

    path('', views.login_views, name='index'),
    path('home/', views.home, name='home'),
    path('cerrar_sesion/', views.cerrar_sesion, name='cerrar_sesion'),
    path('enviar_correo/', views.enviar_correo, name='enviar_correo'),
    path('generar_reporte_pdf', views.generar_reporte_pdf, name='generar_reporte_pdf'),
    path('generar_reporte', views.generar_reporte, name='generar_reporte'),
    
    #-----------------------------------Empleado-----------------------------------
    path('empleado/empleado.html/', views.empleado, name='empleado'),
    path('registrarEmpleado/', views.registrarEmpleado, name='registrarEmpleado'),
    path('editarEmpleado/<idEmpleado>/', views.editarEmpleado, name='editarEmpleado'),
    
    #-----------------------------------Satelite-----------------------------------
    path('satelite/satelite.html/', views.satelite, name='satelite'),
    path('registrarSatelite/', views.registrarSatelite, name='registrarSatelite'),
    path('editarSatelite/<idSatelite>/', views.editarSatelite, name='editarSatelite'),
    
    #-----------------------------------Proveedor-----------------------------------
    path('proveedor/proveedor.html/', views.proveedores, name='proveedor'),
    path('registrarProveedor/', views.registrarProveedor, name='registrarProveedor'),
    path('editarProveedor/<idProveedor>/', views.editarProveedor, name='editarProveedor'),
    
    #-----------------------------------Cliente-----------------------------------
    path('cliente/cliente.html/', views.cliente, name='cliente'),
    path('registrarCliente/', views.registrarCliente, name='registrarCliente'),
    path('editarCliente/<idCliente>/', views.editarCliente, name='editarCliente'),
    
    #-----------------------------------FlujoInventario-----------------------------------
    path('flujoInventario/vistaSatelite.html/', views.vistaSatelite, name='vistaSatelite'),
    path('marcar_entregado/<idCorte>/', views.marcar_entregado, name='marcar_entregado'),
    path('flujoInventario/flujoInventario.html/', views.flujoInventario, name='flujoInventario'),
    path('registroFlujo/', views.registroFlujo, name='registroFlujo'),
    path('editarFlujo/<idComprovante>/', views.editarFlujo, name='editarFlujo'),
    path('flujoInventario/registrarCorte.html/', views.registrarCorte, name='registrarCorte'),
    path('eliminarFlujo/<idComprovante>/', views.eliminarFlujo, name='eliminarFlujo'),
    
    #-----------------------------------MateriaPrima-----------------------------------
    path('materiaPrima/materiaPrima.html/', views.materiaPrima, name='materiaPrima'),
    path('registrarMaterial/', views.registrarMaterial, name='registrarMaterial'),
    path('editarMaterial/<idMaterial>/', views.editarMaterial, name='editarMaterial'),
    
    #-----------------------------------Productos-----------------------------------
    path('producto/producto.html/', views.productos, name='producto'),
    path('registrarProducto/', views.registrarProducto, name='registrarProducto'),
    path('editarProducto/<idProducto>/', views.editarProducto, name='editarProducto'),
    
    #-----------------------------------Devoluciones-----------------------------------
    path('devolucion/devolucion.html/', views.devolucion, name='devolucion'),
    path('registrarDevolucion/', views.registrarDevolucion, name='registrarDevolucion'),
    path('editarDevolucion/<idDevolucion>/', views.editarDevolucion, name='editarDevolucion'),
    path('eliminarDevolucion/<idDevolucion>/', views.eliminarDevolucion, name='eliminarDevolucion'),
    
    #-----------------------------------Ventas-----------------------------------
    path('ventas/ventas.html/', views.ventas, name='ventas'),
    path('registrarVenta/', views.registrarVenta, name='registrarVenta'),
    path('editarVenta/<idComprovante>/', views.editarVenta, name='editarVenta'),
    path('eliminarVenta/<idComprovante>/', views.eliminarVenta, name='eliminarVenta'),
]

ShmailySport/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include('Inventario.urls')),
]
urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Inventario/models.py
from django.db import models
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import User, Group

# Create your models here.

class Arl(models.Model):
    idArl = models.AutoField(primary_key=True)
    arl = models.CharField(max_length=30)
    activo = models.BooleanField(default=True)
    
    def __str__(self):
        txt = "{0}"
        return txt.format(self.arl)
    
class Eps(models.Model):
    idEps = models.AutoField(primary_key=True)
    eps = models.CharField(max_length=30)
    activo = models.BooleanField(default=True)
    
    def __str__(self):
        txt = "{0}"
        return txt.format(self.eps)
    
class Ciudad(models.Model):
    idCiudad = models.AutoField(primary_key=True)
    ciudad = models.CharField(max_length=30)
    activo = models.BooleanField(default=True)
    
    def __str__(self):
        txt = "{0}"
        return txt.format(self.ciudad)

class Cargo(models.Model):
    idCargo = models.AutoField(primary_key=True)
    cargo = models.CharField(max_length=30)
    activo = models.BooleanField(default=True)

    def __str__(self):
        return self.cargo

class MateriaPrima(models.Model):
    idMaterial = models.AutoField(primary_key=True)
    material = models.CharField(max_length=30)
    cantidadMaterial = models.FloatField(default=0.0)
    medidas = [
        ('metros','Metros'),
        ('kilos','Kilos'),
        ('unidades','Unidades')
    ]
    medida = models.CharField(max_length=20, choices=medidas, default='metros')
    activo = models.BooleanField(default=True)
    
    def __str__(self):
        txt = "{0}"
        return txt.format(self.material)
    
class Producto(models.Model):
    idProducto = models.AutoField(primary_key=True)
    producto = models.CharField(max_length=30)
    cantidadProducto = models.PositiveIntegerField(default=0)
    activo = models.BooleanField(default=True)
    
    def __str__(self):
        txt = "{0}"
        return txt.format(self.producto)

class Personas(models.Model):
    documento = models.PositiveIntegerField(primary_key=True)
    nombres = models.CharField(max_length=50)
    apellidos = models.CharField(max_length=50)
    direccion = models.CharField(max_length=50, default='Calle/Carrera 00 sur/norte #00-00')
    correo = models.CharField(max_length=50)
    celular = models.PositiveIntegerField()
    fechaNac = models.DateField()
    ciudadPersona = models.ForeignKey(Ciudad, null=False, blank=False, default=1, on_delete=models.CASCADE)
    sexos = [
        ('femenino', 'Femenino'),
        ('masculino', 'Masculino')
    ]
    sexo = models.CharField(max_length=20, choices=sexos, default='femenino')
    
    def __str__(self):
        txt = "{0}, {1} {2} cel:{3}"
        return txt.format(self.documento, self.nombres, self.apellidos, self.celular)
    
class Satelites(models.Model):
    idSatelite = models.AutoField(primary_key=True)
    docSatelite = models.ForeignKey(Personas, null=False, blank=False, on_delete=models.CASCADE)
    activo = models.BooleanField(default=True)

    def tiene_cortes_activos(self):
        return self.cortes.filter(entregado=False).exists()

    def __str__(self):
        txt = "{0}"
        return txt.format(self.docSatelite.apellidos)

class Proveedor(models.Model):
    idProveedor = models.AutoField(primary_key=True)
    docProveedor = models.ForeignKey(Personas, null=False, blank=False, on_delete=models.CASCADE)
    activo = models.BooleanField(default=True)

    def __str__(self):
        txt = "{0}"
        return txt.format(self.docProveedor.apellidos)

class Cliente(models.Model):
    idCliente = models.AutoField(primary_key=True)
    docCliente = models.ForeignKey(Personas, null=False, blank=False, on_delete=models.CASCADE)
    activo = models.BooleanField(default=True)
    
    def __str__(self):
        txt = "{0}"
        return txt.format(self.docCliente.apellidos)

class Empleado(models.Model):
    idEmpleado = models.AutoField(primary_key=True)
    docEmpleado = models.ForeignKey(Personas, null=False, blank=False, on_delete=models.CASCADE)
    arlEmpleado = models.ForeignKey(Arl, null=False, blank=False, on_delete=models.CASCADE)
    epsEmpleado = models.ForeignKey(Eps, null=False, blank=False, on_delete=models.CASCADE)
    cargo = models.ForeignKey(Cargo, null=False, blank=False, on_delete=models.CASCADE)
    activo = models.BooleanField(default=True)
    contraseña = models.CharField(max_length=30, default='')

    def __str__(self) -> str:
        return f"{self.docEmpleado.documento}, {self.docEmpleado.apellidos}, {self.cargo.cargo}"
    
    def save(self, *args, **kwargs):
        if not self.idEmpleado:  
            self.contraseña = make_password(self.contraseña)
            user = User.objects.create_user(username=self.docEmpleado.documento, password=self.contraseña)
            group = Group.objects.get(name=self.cargo.cargo)  # Asegúrate de que el modelo Cargo tiene un campo llamado 'cargo' que contiene el nombre del cargo
            user.groups.add(group)
            user.save()
        super().save(*args, **kwargs)
    
class Corte(models.Model):
    idCorte = models.AutoField(primary_key=True)
    materialCorte = models.ForeignKey(MateriaPrima, null=False, blank=False, on_delete=models.CASCADE)
    cantidadCorte = models.FloatField(default=0.0)
    medidas = [
        ('m','metros'),
        ('k','kilos')
    ]
    medida = models.CharField(max_length=1, choices=medidas, default='m')
    productoCorte = models.ForeignKey(Producto, null=False, blank=False, on_delete=models.CASCADE)
    entregado = models.BooleanField(default=False)
    fechaCorte = models.DateTimeField(auto_now_add=True)
    
    satelite = models.ForeignKey(Satelites, related_name='cortes', on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        txt = "{0}, Material: {1}, Producto Final: {2}, {3}"
        return txt.format(self.idCorte, self.materialCorte.material, self.productoCorte.producto, self.fechaCorte)    
    
class FlujoInventario(models.Model):
    idComprovante = models.AutoField(primary_key=True)
    docEmpleado = models.ForeignKey(Empleado, null=False, blank=False, on_delete=models.CASCADE)
    proveedorFlujo = models.ForeignKey(Proveedor, null=True, blank=True, on_delete=models.CASCADE)
    materialFlu = models.ForeignKey(MateriaPrima, null=True, blank=True, on_delete=models.CASCADE)
    flujoCliente = models.ForeignKey(Cliente, null=True, blank=True, on_delete=models.CASCADE)
    flujoSatelite = models.ForeignKey(Satelites, null=True, blank=True, on_delete=models.CASCADE)
    flujoProducto = models.ForeignKey(Producto, null=True, blank=True, on_delete=models.CASCADE)
    flujoCorte = models.ForeignKey(Corte, null=True, blank=True, on_delete=models.CASCADE)
    insumos = models.ManyToManyField(MateriaPrima, related_name='flujos_inventario')
    flujos = [
        ('entrada', 'Entrada'),
        ('salida', 'Salida'),
        ('venta', 'Venta'),
    ]
    flujo = models.CharField(max_length=20, choices=flujos, default='entrada')
    fechaFlujo = models.DateTimeField(auto_now_add=True)
    cantidadFlujo = models.FloatField(null=True, blank=True)
    
    def __str__(self):
        txt = "{0}, {1}, {2}: {3} {4}"
        return txt.format(self.idComprovante, self.docEmpleado, self.flujo, self.fechaFlujo, self.cantidadFlujo)
    
class DetalleFlujoInventario(models.Model):
    flujo_inventario = models.ForeignKey(FlujoInventario, on_delete=models.CASCADE)
    materia_prima = models.ForeignKey(MateriaPrima, on_delete=models.CASCADE)
    cantidad = models.FloatField()
    cantidad_insumo = models.FloatField(default=0)
    
class Devoluciones(models.Model):
    idDevolucion = models.AutoField(primary_key=True)
    devoEmpleado = models.ForeignKey(Empleado, default=None, null=False, blank=False, on_delete=models.CASCADE)
    devoSatelite = models.ForeignKey(Satelites, default=None, null=True, blank=True, on_delete=models.CASCADE)
    devoProveedor = models.ForeignKey(Proveedor, default=None, null=True, blank=True, on_delete=models.CASCADE)
    devoProducto = models.ForeignKey(Producto, default=None, null=True, blank=True, on_delete=models.CASCADE)
    devoMaterial = models.ForeignKey(MateriaPrima, default=None, null=True, blank=True, on_delete=models.CASCADE)
    flujos = [
        ('entrada', 'Entrada'),
        ('salida', 'Salida')
    ]
    flujo = models.CharField(max_length=20, choices=flujos, default='entrada')
    motivo = models.CharField(max_length=255, default="")
    cantidadDevo = models.FloatField(null=False, blank=False, default=0.0)
    fechaDevolucion = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        txt = "{0}, {1}"
        return txt.format(self.idDevolucion, self.fechaDevolucion)
    
    

Inventario/templates/flujoInventario/editarFlujo.html
{% extends 'home.html' %}
{% block content %}

{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edición de Clientes</title>
    <link rel="stylesheet" href="{% static 'css/formulario.css' %}">
</head>
<body>
<h1>Editar Flujo de Inventario</h1>
<form method="post" id="inventory-form">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    {{ formset.management_form }}
    <table id="dynamic-fields-table">
        {% for form in formset %}
        <tr class="form-row">
            {% for field in form.visible_fields %}
            <td>{{ field.errors }} {{ field }}</td>
            {% endfor %}
        </tr>
        {% endfor %}
    </table>
    <button type="submit">Guardar cambios</button>
</form>

<script>
    function mostrarCamposUtilizados() {
        // Obtener todos los campos del formulario
        var campos = document.querySelectorAll('#inventory-form input, #inventory-form select');

        // Iterar sobre cada campo y verificar si tiene algún valor
        campos.forEach(function (campo) {
            if (campo.type !== 'submit' && campo.type !== 'button') {
                var fila = campo.closest('.form-row'); // Obtener la fila que contiene el campo
                if (campo.value.trim() !== '' || campo.checked || campo.type === 'number') {
                    fila.style.display = ''; // Mostrar la fila si el campo tiene un valor
                } else {
                    fila.style.display = 'none'; // Ocultar la fila si el campo está vacío
                }
            }
        });
    }

    // Ejecutar la función cuando se cargue la página y cada vez que cambie un campo del formulario
    window.addEventListener('load', mostrarCamposUtilizados);
    document.querySelectorAll('#inventory-form input, #inventory-form select').forEach(function (campo) {
        campo.addEventListener('change', mostrarCamposUtilizados);
    });
</script>

</body>
</html>

{% endblock %}

Inventario/templates/flujoInventario/flujoInventario.html
{% extends 'home.html' %}
{% block content %}

{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lista de Productos</title>
    <link rel="stylesheet" href="{% static 'css/vistas.css' %}">
</head>
<body>
    <div class="container">
        <h1>Listado de Flujos</h1>

        <input type="text" id="searchInput" placeholder="Buscar...">
        <button onclick="searchFunction()">Buscar</button>
      
        <a href="{% url 'registroFlujo' %}" class="btn btn-secondary">Resgistrar Flujo</a>
        
        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Id</th>
                        <th>Empleado</th>
                        <th>Proveedor</th>
                        <th>Material</th>
                        <th>Satelite</th>
                        <th>Producto</th>
                        <th>Corte</th>
                        <th>Insumos</th>
                        <th>Flujo</th>
                        <th>Cantidad</th>
                        <th>Fecha</th>
                        <th>Opciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for fli in flujoInventario %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ fli.idComprovante }}</td>
                                <td>{{ fli.docEmpleado.docEmpleado }}</td>
                                <td>{{ fli.proveedorFlujo.docProveedor }}</td>
                                <td>{{ fli.materialFlu.material }}</td>
                                <td>{{ fli.flujoSatelite.docSatelite }}</td>
                                <td>{{ fli.flujoProducto.producto }}</td>
                                <td>{{ fli.flujoCorte.idCorte }}</td>
                                <td>
                                    {% for insumo in fli.insumos.all %}
                                        {{ insumo.material }}{% if not forloop.last %}, {% endif %}
                                    {% endfor %}
                                </td>
                                <td>{{ fli.flujo }}</td>
                                <td>{{ fli.cantidadFlujo }}</td>
                                <td>{{ fli.fechaFlujo }}</td>
                                <td>
                                  <a href="/eliminarFlujo/{{ fli.idComprovante }}" class="btn btn-danger" onclick="return confirm('¿Estás seguro de que deseas eliminar este flujo?')">Eliminar</a>
                                  <a href="/editarFlujo/{{ fli.idComprovante }}" class="btn btn-info">Editar</a>
                                </td>
                            </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <script>
        function searchFunction() {
          // Obtener el valor del campo de búsqueda
          var input, filter, table, tr, td, i, txtValue;
          input = document.getElementById("searchInput");
          filter = input.value.toUpperCase();
          table = document.querySelector(".table");
          tr = table.getElementsByTagName("tr");
        
          // Iterar sobre todas las filas y ocultar las que no coincidan con la búsqueda
          for (i = 0; i < tr.length; i++) {
            td = tr[i].getElementsByTagName("td");
            for (var j = 0; j < td.length; j++) {
              if (td[j]) {
                txtValue = td[j].textContent || td[j].innerText;
                if (txtValue.toUpperCase().indexOf(filter) > -1) {
                  tr[i].style.display = "";
                  break;
                } else {
                  tr[i].style.display = "none";
                }
              }
            }
          }
        }
    </script>
        
</body>

</html>

{% endblock %}

Inventario/templates/flujoInventario/registrarCorte.html
{% extends 'home.html' %}
{% block content %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Edición de Clientes</title>
    <link rel="stylesheet" href="{% static 'css/forms.css' %}">
    <script>
      function validateForm() {
          var inputs = document.getElementById("salesForm").getElementsByTagName('input');
          for(var i=0; i < inputs.length; i++) {
              if(inputs[i].type == 'text' && inputs[i].value == '') {
                  alert('Por favor, rellena todos los campos para seguir con el proceso de registro.');
                  return false;
              }
          }
          if(confirm('¿Estás seguro de que quieres registrar este corte?')) {
              alert('Corte registrado con éxito.');
              return true;
          } else {
              return false;
          }
      }
  </script>
  </head>
  <body>
    <div class="container">
      <h1>Registrar Nuevo Corte</h1>
      <form id="salesForm" method="POST" onsubmit="return validateForm();">
        {% csrf_token %}
        <table>
          {{ form.as_table }}
        </table>
        <input class="cbp-mc-submit btn btn-primary" type="submit" value="Registrar" />
        <a href="{% url 'registroFlujo' %}" class="btn btn-info">Volver</a>
      </form>
    </div>
  </body>
</html>

{% endblock %}

Inventario/templates/flujoInventario/registroFlujo.html
{% extends 'home.html' %} {% block content %} {% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Gestión de Inventario</title>
    <link rel="stylesheet" href="{% static 'css/formulario.css' %}" />
  </head>
  <body>
    <div>
      <button id="material-btn" class="btn btn-primary">
        Gestión de Material
      </button>
      <button id="corte-btn" class="btn btn-primary">Gestión de Corte</button>
      <button id="producto-btn" class="btn btn-primary">
        Gestión de Producto
      </button>
    </div>

    <div id="form-container" class="container mt-4">
      <table class="table">
        <form id="registroForm" method="post" onsubmit="return validateForm()">
          {% csrf_token %}
          <tr>
            <td><label id="docEmpleado" for="docEmpleado" class="form-label">Empleado</label></td>
            <td>{{form.docEmpleado}}</td>
          </tr>
          <tr class="hidden producto-fields">
            <td><label id="flujoSatelite1" for="flujoSatelite" class="form-label">Satelite</label></td>
            <td>{{form.flujoSatelite}}</td>
          </tr>
          <tr class="hidden material-fields">
            <td><label id="proveedorFlujo" for="proveedorFlujo" class="form-label">Proveedor</label></td>
            <td>{{form.proveedorFlujo}}</td>
          </tr>
          <tr class="hidden material-fields">
            <td><label id="materialFlu" for="materialFlu" class="form-label">Material</label></td>
            <td>{{form.materialFlu}}</td>
          </tr>
          <tr class="hidden corte-fields">
            <td><label id="flujoSatelite2" for="flujoSatelite" class="form-label">Satelite</label></td>
            <td>{{form.flujoSatelite}}</td>
          </tr>
          <tr class="hidden corte-fields">
            <td><label id="flujoCorte" for="flujoCorte" class="form-label">Corte</label></td>
            <td>{{form.flujoCorte}}</td>
          </tr>
          <tr class="hidden corte-fields">
            <td><label for="id_insumos" class="form-label">Insumos</label></td>
            <td>
                <div id="id_insumos" class="checkbox-list">
                    {% for insumo in insumos %}
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" name="insumos" id="insumo_{{ insumo.id }}" value="{{ insumo.id }}">
                            <label class="form-check-label" for="insumo_{{ insumo.idMaterial }}">{{ insumo.material }}</label>
                        </div>
                    {% endfor %}
                </div>
            </td>
          </tr>
          <tr class="hidden producto-fields">
            <td><label id="flujoProducto" for="flujoProducto" class="form-label">Producto</label></td>
            <td>{{form.flujoProducto}}</td>
          </tr>
          <tr>
            <td><label id="flujo" for="flujo" class="form-label">Flujo</label></td>
            <td>{{form.flujo}}</td>
          </tr>
          <tr >
            <td><label id="cantidadFlujo1" for="cantidadFlujo" class="form-label">Cantidad</label></td>
            <td><input type="number" class="form-control" id="cantidadFlujo" name="cantidadFlujo"/></td>
          </tr>
          <tr>
            <td colspan="2">
              <button type="submit" class="btn btn-primary">Guardar</button>
              <a href="{% url 'registrarCorte' %}" class="btn btn-info hidden corte-fields">Registrar Corte</a>
            </td>
          </tr>
        </form>
      </table>
    </div>

    <div id="confirmacionRegistro" class="modal" style="width: 60%; margin: 0 auto">
      <div class="modal-content" style="padding: 20px">
        <span class="close" style="float: right; font-size: 28px; font-weight: bold">&times;</span>
        <p style="font-size: 20px">¿Estás seguro de que deseas hacer este registro?</p>
        <div style="text-align: center; margin-top: 20px">
          <button id="confirmarBtn" class="btn-confirmar" style="font-size: 18px; padding: 10px 20px; margin-right: 10px">¡Sí, registrar!</button>
          <button id="cancelarBtn" class="btn-cancelar" style="font-size: 18px; padding: 10px 20px">Cancelar</button>
        </div>
      </div>
    </div>

    <script>
      function validateForm() {
        const materialBtn = document.getElementById("material-btn");
        const corteBtn = document.getElementById("corte-btn");
        const productoBtn = document.getElementById("producto-btn");

        materialBtn.addEventListener("click", () => {
            materialBtn.classList.add("active");
            corteBtn.classList.remove("active");
            productoBtn.classList.remove("active");

            materialFields.forEach((field) => field.classList.remove("hidden"));
            corteFields.forEach((field) => field.classList.add("hidden"));
            productoFields.forEach((field) => field.classList.add("hidden"));
        });

        corteBtn.addEventListener("click", () => {
            materialBtn.classList.remove("active");
            corteBtn.classList.add("active");
            productoBtn.classList.remove("active");

            materialFields.forEach((field) => field.classList.add("hidden"));
            corteFields.forEach((field) => field.classList.remove("hidden"));
            productoFields.forEach((field) => field.classList.add("hidden"));
        });

        productoBtn.addEventListener("click", () => {
            materialBtn.classList.remove("active");
            corteBtn.classList.remove("active");
            productoBtn.classList.add("active");

            materialFields.forEach((field) => field.classList.add("hidden"));
            corteFields.forEach((field) => field.classList.add("hidden"));
            productoFields.forEach((field) => field.classList.remove("hidden"));
        });
        }

        const materialFields = document.querySelectorAll(".material-fields");
        const corteFields = document.querySelectorAll(".corte-fields");
        const productoFields = document.querySelectorAll(".producto-fields");

        validateForm();

      var registroForm = document.getElementById("registroForm");
      var confirmacionRegistro = document.getElementById(
        "confirmacionRegistro"
      );
      registroForm.addEventListener("submit", function (event) {
        event.preventDefault();

        if (validarCampos()) {
          confirmacionRegistro.style.display = "block";
        } else {
          alert("Por favor, rellene todos los campos antes de continuar.");
        }
      });

      function validarCampos() {
        var formElements = registroForm.elements;
        console.log("Validando campos...");

        // Lista de nombres de campos que son obligatorios cuando se selecciona un cierto botón
        var camposObligatoriosMaterial = ["docEmpleado", "proveedorFlujo","materialFlu", "flujo"];
        var camposObligatoriosCorte = ["docEmpleado", "flujoSatelite2", "flujoCorte", "flujo"];
        var camposObligatoriosProducto = ["docEmpleado", "flujoSatelite1", "flujoProducto", "flujo"];

        // Verificar qué botón está seleccionado
        var materialBtnSeleccionado = document.getElementById("material-btn").classList.contains("active");
        var corteBtnSeleccionado = document.getElementById("corte-btn").classList.contains("active");
        var productoBtnSeleccionado = document.getElementById("producto-btn").classList.contains("active");

        for (var i = 0; i < formElements.length; i++) {
            if (materialBtnSeleccionado && camposObligatoriosMaterial.includes(formElements[i].name) && formElements[i].value.trim() === "") {
            console.log("Campo vacío encontrado: ", formElements[i].name);
            return false;
            }

            if (corteBtnSeleccionado && camposObligatoriosCorte.includes(formElements[i].name) && formElements[i].value.trim() === "") {
            console.log("Campo vacío encontrado: ", formElements[i].name);
            return false;
            }

            if (productoBtnSeleccionado && camposObligatoriosProducto.includes(formElements[i].name) && formElements[i].value.trim() === "") {
            console.log("Campo vacío encontrado: ", formElements[i].name);
            return false;
            }
        }
        return true;
        }

      var confirmarBtn = document.getElementById("confirmarBtn");
      var cancelarBtn = document.getElementById("cancelarBtn");
      confirmarBtn.addEventListener("click", function () {
        registroForm.submit();
      });
      cancelarBtn.addEventListener("click", function () {
        confirmacionRegistro.style.display = "none";
      });
    </script>
  </body>
</html>

{% endblock %}