Inventario/urls.py
from django.urls import path
from . import views

urlpatterns = [
    #------------------------Index y login------------------------------------------

    path('', views.login_views, name='index'),
    path('home/', views.home, name='home'),
    path('cerrar_sesion/', views.cerrar_sesion, name='cerrar_sesion'),
    path('enviar_correo/', views.enviar_correo, name='enviar_correo'),
    path('generar_reporte_pdf', views.generar_reporte_pdf, name='generar_reporte_pdf'),
    path('generar_reporte', views.generar_reporte, name='generar_reporte'),
    
    #-----------------------------------Empleado-----------------------------------
    path('empleado/empleado.html/', views.empleado, name='empleado'),
    path('registrarEmpleado/', views.registrarEmpleado, name='registrarEmpleado'),
    path('editarEmpleado/<idEmpleado>/', views.editarEmpleado, name='editarEmpleado'),
    
    #-----------------------------------Satelite-----------------------------------
    path('satelite/satelite.html/', views.satelite, name='satelite'),
    path('registrarSatelite/', views.registrarSatelite, name='registrarSatelite'),
    path('editarSatelite/<idSatelite>/', views.editarSatelite, name='editarSatelite'),
    
    #-----------------------------------Proveedor-----------------------------------
    path('proveedor/proveedor.html/', views.proveedores, name='proveedor'),
    path('registrarProveedor/', views.registrarProveedor, name='registrarProveedor'),
    path('editarProveedor/<idProveedor>/', views.editarProveedor, name='editarProveedor'),
    
    #-----------------------------------Cliente-----------------------------------
    path('cliente/cliente.html/', views.cliente, name='cliente'),
    path('registrarCliente/', views.registrarCliente, name='registrarCliente'),
    path('editarCliente/<idCliente>/', views.editarCliente, name='editarCliente'),
    
    #-----------------------------------FlujoInventario-----------------------------------
    path('flujoInventario/vistaSatelite.html/', views.vistaSatelite, name='vistaSatelite'),
    path('marcar_entregado/<idCorte>/', views.marcar_entregado, name='marcar_entregado'),
    path('flujoInventario/flujoInventario.html/', views.flujoInventario, name='flujoInventario'),
    path('registroFlujo/', views.registroFlujo, name='registroFlujo'),
    path('editarFlujo/<idComprovante>/', views.editarFlujo, name='editarFlujo'),
    path('flujoInventario/registrarCorte.html/', views.registrarCorte, name='registrarCorte'),
    path('eliminarFlujo/<idComprovante>/', views.eliminarFlujo, name='eliminarFlujo'),
    
    #-----------------------------------MateriaPrima-----------------------------------
    path('materiaPrima/materiaPrima.html/', views.materiaPrima, name='materiaPrima'),
    path('registrarMaterial/', views.registrarMaterial, name='registrarMaterial'),
    path('editarMaterial/<idMaterial>/', views.editarMaterial, name='editarMaterial'),
    
    #-----------------------------------Productos-----------------------------------
    path('producto/producto.html/', views.productos, name='producto'),
    path('registrarProducto/', views.registrarProducto, name='registrarProducto'),
    path('editarProducto/<idProducto>/', views.editarProducto, name='editarProducto'),
    
    #-----------------------------------Devoluciones-----------------------------------
    path('devolucion/devolucion.html/', views.devolucion, name='devolucion'),
    path('registrarDevolucion/', views.registrarDevolucion, name='registrarDevolucion'),
    path('editarDevolucion/<idDevolucion>/', views.editarDevolucion, name='editarDevolucion'),
    path('eliminarDevolucion/<idDevolucion>/', views.eliminarDevolucion, name='eliminarDevolucion'),
    
    #-----------------------------------Ventas-----------------------------------
    path('ventas/ventas.html/', views.ventas, name='ventas'),
    path('registrarVenta/', views.registrarVenta, name='registrarVenta'),
    path('editarVenta/<idComprovante>/', views.editarVenta, name='editarVenta'),
    path('eliminarVenta/<idComprovante>/', views.eliminarVenta, name='eliminarVenta'),
]

ShmailySport/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include('Inventario.urls')),
]
urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Inventario/models.py
from django.db import models
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import User, Group

# Create your models here.

class Arl(models.Model):
    idArl = models.AutoField(primary_key=True)
    arl = models.CharField(max_length=30)
    activo = models.BooleanField(default=True)
    
    def __str__(self):
        txt = "{0}"
        return txt.format(self.arl)
    
class Eps(models.Model):
    idEps = models.AutoField(primary_key=True)
    eps = models.CharField(max_length=30)
    activo = models.BooleanField(default=True)
    
    def __str__(self):
        txt = "{0}"
        return txt.format(self.eps)
    
class Ciudad(models.Model):
    idCiudad = models.AutoField(primary_key=True)
    ciudad = models.CharField(max_length=30)
    activo = models.BooleanField(default=True)
    
    def __str__(self):
        txt = "{0}"
        return txt.format(self.ciudad)

class Cargo(models.Model):
    idCargo = models.AutoField(primary_key=True)
    cargo = models.CharField(max_length=30)
    activo = models.BooleanField(default=True)

    def __str__(self):
        return self.cargo

class MateriaPrima(models.Model):
    idMaterial = models.AutoField(primary_key=True)
    material = models.CharField(max_length=30)
    cantidadMaterial = models.FloatField(default=0.0)
    medidas = [
        ('metros','Metros'),
        ('kilos','Kilos'),
        ('unidades','Unidades')
    ]
    medida = models.CharField(max_length=20, choices=medidas, default='metros')
    activo = models.BooleanField(default=True)
    
    def __str__(self):
        txt = "{0}"
        return txt.format(self.material)
    
class Producto(models.Model):
    idProducto = models.AutoField(primary_key=True)
    producto = models.CharField(max_length=30)
    cantidadProducto = models.PositiveIntegerField(default=0)
    activo = models.BooleanField(default=True)
    
    def __str__(self):
        txt = "{0}"
        return txt.format(self.producto)

class Personas(models.Model):
    documento = models.PositiveIntegerField(primary_key=True)
    nombres = models.CharField(max_length=50)
    apellidos = models.CharField(max_length=50)
    direccion = models.CharField(max_length=50, default='Calle/Carrera 00 sur/norte #00-00')
    correo = models.CharField(max_length=50)
    celular = models.PositiveIntegerField()
    fechaNac = models.DateField()
    ciudadPersona = models.ForeignKey(Ciudad, null=False, blank=False, default=1, on_delete=models.CASCADE)
    sexos = [
        ('femenino', 'Femenino'),
        ('masculino', 'Masculino')
    ]
    sexo = models.CharField(max_length=20, choices=sexos, default='femenino')
    
    def __str__(self):
        txt = "{0}, {1} {2} cel:{3}"
        return txt.format(self.documento, self.nombres, self.apellidos, self.celular)
    
class Satelites(models.Model):
    idSatelite = models.AutoField(primary_key=True)
    docSatelite = models.ForeignKey(Personas, null=False, blank=False, on_delete=models.CASCADE)
    activo = models.BooleanField(default=True)

    def tiene_cortes_activos(self):
        return self.cortes.filter(entregado=False).exists()

    def __str__(self):
        txt = "{0}"
        return txt.format(self.docSatelite.apellidos)

class Proveedor(models.Model):
    idProveedor = models.AutoField(primary_key=True)
    docProveedor = models.ForeignKey(Personas, null=False, blank=False, on_delete=models.CASCADE)
    activo = models.BooleanField(default=True)

    def __str__(self):
        txt = "{0}"
        return txt.format(self.docProveedor.apellidos)

class Cliente(models.Model):
    idCliente = models.AutoField(primary_key=True)
    docCliente = models.ForeignKey(Personas, null=False, blank=False, on_delete=models.CASCADE)
    activo = models.BooleanField(default=True)
    
    def __str__(self):
        txt = "{0}"
        return txt.format(self.docCliente.apellidos)

class Empleado(models.Model):
    idEmpleado = models.AutoField(primary_key=True)
    docEmpleado = models.ForeignKey(Personas, null=False, blank=False, on_delete=models.CASCADE)
    arlEmpleado = models.ForeignKey(Arl, null=False, blank=False, on_delete=models.CASCADE)
    epsEmpleado = models.ForeignKey(Eps, null=False, blank=False, on_delete=models.CASCADE)
    cargo = models.ForeignKey(Cargo, null=False, blank=False, on_delete=models.CASCADE)
    activo = models.BooleanField(default=True)
    contraseña = models.CharField(max_length=30, default='')

    def __str__(self) -> str:
        return f"{self.docEmpleado.documento}, {self.docEmpleado.apellidos}, {self.cargo.cargo}"
    
    def save(self, *args, **kwargs):
        if not self.idEmpleado:  
            self.contraseña = make_password(self.contraseña)
            user = User.objects.create_user(username=self.docEmpleado.documento, password=self.contraseña)
            group = Group.objects.get(name=self.cargo.cargo)  # Asegúrate de que el modelo Cargo tiene un campo llamado 'cargo' que contiene el nombre del cargo
            user.groups.add(group)
            user.save()
        super().save(*args, **kwargs)
    
class Corte(models.Model):
    idCorte = models.AutoField(primary_key=True)
    materialCorte = models.ForeignKey(MateriaPrima, null=False, blank=False, on_delete=models.CASCADE)
    cantidadCorte = models.FloatField(default=0.0)
    medidas = [
        ('m','metros'),
        ('k','kilos')
    ]
    medida = models.CharField(max_length=1, choices=medidas, default='m')
    productoCorte = models.ForeignKey(Producto, null=False, blank=False, on_delete=models.CASCADE)
    entregado = models.BooleanField(default=False)
    fechaCorte = models.DateTimeField(auto_now_add=True)
    
    satelite = models.ForeignKey(Satelites, related_name='cortes', on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        txt = "{0}, Material: {1}, Producto Final: {2}, {3}"
        return txt.format(self.idCorte, self.materialCorte.material, self.productoCorte.producto, self.fechaCorte)    
    
class FlujoInventario(models.Model):
    idComprovante = models.AutoField(primary_key=True)
    docEmpleado = models.ForeignKey(Empleado, null=False, blank=False, on_delete=models.CASCADE)
    proveedorFlujo = models.ForeignKey(Proveedor, null=True, blank=True, on_delete=models.CASCADE)
    materialFlu = models.ForeignKey(MateriaPrima, null=True, blank=True, on_delete=models.CASCADE)
    flujoCliente = models.ForeignKey(Cliente, null=True, blank=True, on_delete=models.CASCADE)
    flujoSatelite = models.ForeignKey(Satelites, null=True, blank=True, on_delete=models.CASCADE)
    flujoProducto = models.ForeignKey(Producto, null=True, blank=True, on_delete=models.CASCADE)
    flujoCorte = models.ForeignKey(Corte, null=True, blank=True, on_delete=models.CASCADE)
    insumos = models.ManyToManyField(MateriaPrima, related_name='flujos_inventario')
    flujos = [
        ('entrada', 'Entrada'),
        ('salida', 'Salida'),
        ('venta', 'Venta'),
    ]
    flujo = models.CharField(max_length=20, choices=flujos, default='entrada')
    fechaFlujo = models.DateTimeField(auto_now_add=True)
    cantidadFlujo = models.FloatField(null=True, blank=True)
    
    def __str__(self):
        txt = "{0}, {1}, {2}: {3} {4}"
        return txt.format(self.idComprovante, self.docEmpleado, self.flujo, self.fechaFlujo, self.cantidadFlujo)
    
class DetalleFlujoInventario(models.Model):
    flujo_inventario = models.ForeignKey(FlujoInventario, on_delete=models.CASCADE)
    materia_prima = models.ForeignKey(MateriaPrima, on_delete=models.CASCADE)
    cantidad = models.FloatField()
    cantidad_insumo = models.FloatField(default=0)
    
class Devoluciones(models.Model):
    idDevolucion = models.AutoField(primary_key=True)
    devoEmpleado = models.ForeignKey(Empleado, default=None, null=False, blank=False, on_delete=models.CASCADE)
    devoSatelite = models.ForeignKey(Satelites, default=None, null=True, blank=True, on_delete=models.CASCADE)
    devoProveedor = models.ForeignKey(Proveedor, default=None, null=True, blank=True, on_delete=models.CASCADE)
    devoProducto = models.ForeignKey(Producto, default=None, null=True, blank=True, on_delete=models.CASCADE)
    devoMaterial = models.ForeignKey(MateriaPrima, default=None, null=True, blank=True, on_delete=models.CASCADE)
    flujos = [
        ('entrada', 'Entrada'),
        ('salida', 'Salida')
    ]
    flujo = models.CharField(max_length=20, choices=flujos, default='entrada')
    motivo = models.CharField(max_length=255, default="")
    cantidadDevo = models.FloatField(null=False, blank=False, default=0.0)
    fechaDevolucion = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        txt = "{0}, {1}"
        return txt.format(self.idDevolucion, self.fechaDevolucion)
    
    

Inventario/templates/materiaPrima/editarMaterial.html
{% extends 'home.html' %}
{% block content %}

{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Editar Materia Prima</title>
    <link rel="stylesheet" href="{% static 'css/forms.css' %}">
</head>
<body>
    <div class="container">
        <h1>Editar Materia Prima</h1>
        <form method="post">
            {% csrf_token %}
            <table>
                {{ form.as_table }}
            </table>
            <div class="cbp-mc-submit-wrap">
                <input class="cbp-mc-submit btn btn-primary" type="submit" value="Guardar Cambios" />
            </div>
        </form>
    </div>
</body>
</html>

{% endblock %}

Inventario/templates/materiaPrima/materiaPrima.html
{% extends 'home.html' %} 
{% block content %} 

{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Lista de Materias Primas</title>
  <link rel="stylesheet" href="{% static 'css/vistas.css' %}" />
</head>
<body>
		<!-- En la sección del cuerpo de tu plantilla materiaPrima.html -->
	<div class="container">
		<h1>Lista de Materias Primas</h1>

		<!-- Agregar el campo de búsqueda -->
		<div class="form-group">
			<input type="text" id="inputBusqueda" class="form-control" placeholder="Buscar...">
		</div>

		<a href="{% url 'registrarMaterial' %}" class="btn btn-secondary">Registrar</a>
		<button id="btnMostrarActivos" class="btn btn-primary">Mostrar Activos</button>
		<button id="btnMostrarInactivos" class="btn btn-warning">Mostrar Inactivos</button>

		<div class="table-responsive">
			<table class="table table-striped">
				<thead>
					<tr>
						<th>#</th>
						<th>ID</th>
						<th>Material</th>
						<th>Cantidad</th>
						<th>Medida</th>
						<th>Edicion</th>
					</tr>
				</thead>
				<tbody>
					{% for materia_prima in materias_primas_activas %}
						<tr class="fila-activa">
							<td>{{ forloop.counter }}</td>
							<td>{{ materia_prima.idMaterial }}</td>
							<td>{{ materia_prima.material }}</td>
							<td>{{ materia_prima.cantidadMaterial }}</td>
							<td>{{ materia_prima.get_medida_display }}</td>
							<td>
								<a href="/editarMaterial/{{ materia_prima.idMaterial }}" class="btn btn-info">Editar</a>
							</td>
							
						</tr>
					{% endfor %}
					{% for materia_prima in materias_primas_inactivas %}
						<tr class="fila-inactiva" style="display: none;">
							<td>{{ forloop.counter }}</td>
							<td>{{ materia_prima.idMaterial }}</td>
							<td>{{ materia_prima.material }}</td>
							<td>{{ materia_prima.cantidadMaterial }}</td>
							<td>{{ materia_prima.get_medida_display }}</td>
							<td>
								<a href="/editarMaterial/{{ materia_prima.idMaterial }}" class="btn btn-info">Editar</a>
							</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</div>
	<script>
		document.addEventListener("DOMContentLoaded", function() {
			var btnMostrarActivos = document.getElementById("btnMostrarActivos");
			var btnMostrarInactivos = document.getElementById("btnMostrarInactivos");
			var filasActivas = document.querySelectorAll(".fila-activa");
			var filasInactivas = document.querySelectorAll(".fila-inactiva");
			var inputBusqueda = document.getElementById("inputBusqueda");
	
			// Evento de escucha para el botón de mostrar activos
			btnMostrarActivos.addEventListener("click", function() {
				filasActivas.forEach(function(fila) {
					fila.style.display = "table-row";
				});
				filasInactivas.forEach(function(fila) {
					fila.style.display = "none";
				});
			});
	
			// Evento de escucha para el botón de mostrar inactivos
			btnMostrarInactivos.addEventListener("click", function() {
				filasActivas.forEach(function(fila) {
					fila.style.display = "none";
				});
				filasInactivas.forEach(function(fila) {
					fila.style.display = "table-row";
				});
			});
	
			// Evento de escucha para el campo de búsqueda
			inputBusqueda.addEventListener("input", function() {
				var textoBusqueda = inputBusqueda.value.toLowerCase();
				filasActivas.forEach(function(fila) {
					var contenidoFila = fila.textContent.toLowerCase();
					if (contenidoFila.includes(textoBusqueda)) {
						fila.style.display = "table-row";
					} else {
						fila.style.display = "none";
					}
				});
				filasInactivas.forEach(function(fila) {
					var contenidoFila = fila.textContent.toLowerCase();
					if (contenidoFila.includes(textoBusqueda)) {
						fila.style.display = "table-row";
					} else {
						fila.style.display = "none";
					}
				});
			});
		});
	</script>
</body>
</html>

{% endblock %}

Inventario/templates/materiaPrima/registrarMaterial.html
{% extends 'home.html' %}
{% block content %}

{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registro de Materia Prima</title>
    <link rel="stylesheet" href="{% static 'css/forms.css' %}">
    <script>
        function validateForm() {
            var inputs = document.getElementById("salesForm").getElementsByTagName('input');
            for(var i=0; i < inputs.length; i++) {
                if(inputs[i].type == 'text' && inputs[i].value == '') {
                    alert('Por favor, rellena todos los campos para seguir con el proceso de registro.');
                    return false;
                }
            }
            if(confirm('¿Estás seguro de que quieres guardar la venta?')) {
                alert('Venta guardada con éxito.');
                return true;
            } else {
                return false;
            }
        }
    </script>
</head>
<body>
    <div class="container">
        <h1>Registro de Materia Prima</h1>
        <form form id="salesForm" method="POST" onsubmit="return validateForm();">
            {% csrf_token %}
            <table>
                {{ form.as_table }}
            </table>
            <input class="cbp-mc-submit btn btn-primary" type="submit" value="Registrar" />
        </form>
    </div>
</body>
</html>

{% endblock %}